name:Generate Datas
on:
  schedule:execute every 12 hours
    -cron:/12 ...
  workflow dispatch:
jobs:
 build:
    name:Jobs to update datas
    runs-on:ubuntu-latest
    steps:
        Snake Animation
      -uses:Platane/skmaster
        id:snake-gir
           github user name:rdsantanali
          svg out path:dist/github-contribution-grid-snake.svg
      -uses:crazy-max/ghaction-github-pages@v2.1.3
        with:
           target branch:output
          builo dir:dist
        env:
           GITHUB TOKEN:$((secrets.GITHUB TOKEN}}
